
// Mock API implementation for tool processing
// In a real app, these would call a backend service.

export interface UploadResponse {
  jobId: string;
}

export interface JobStatusResponse {
  status: 'pending' | 'processing' | 'completed' | 'failed';
  downloadUrl?: string;
  summary?: string;
  error?: string;
}

export async function uploadFile(files: File[], tool: string, options: any): Promise<UploadResponse> {
  console.log('Uploading files for tool:', tool, files, options);
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 1000));
  
  return {
    jobId: `job_${Math.random().toString(36).substr(2, 9)}`
  };
}

export async function pollJobStatus(jobId: string): Promise<JobStatusResponse> {
  // Simulate backend processing
  // Randomly return different statuses to simulate progress
  const rand = Math.random();
  
  if (rand < 0.2) {
    return { status: 'pending' };
  } else if (rand < 0.7) {
    return { status: 'processing' };
  } else if (rand < 0.95) {
    return { 
      status: 'completed', 
      downloadUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      summary: 'This is a mock summary generated by the AI Summarizer tool. It highlights the main points of your PDF document.'
    };
  } else {
    // 5% chance of failure for testing
    return { status: 'failed', error: 'Random processing error occurred' };
  }
}
